// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package generated.smarthome.security;

public interface CameraFeedOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeSecurity.CameraFeed)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes feedData = 1;</code>
   * @return The feedData.
   */
  com.google.protobuf.ByteString getFeedData();
}
