// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package generated.smarthome.security;

public interface DoorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeSecurity.DoorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string doorID = 1;</code>
   * @return The doorID.
   */
  java.lang.String getDoorID();
  /**
   * <code>string doorID = 1;</code>
   * @return The bytes for doorID.
   */
  com.google.protobuf.ByteString
      getDoorIDBytes();
}
