// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyRoutineServices.proto

package generated.smarthome.energy;

public interface EmptyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeEnergy.EmptyRequest)
    com.google.protobuf.MessageOrBuilder {
}
