// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyRoutineServices.proto

package generated.smarthome.energy;

public interface EnergyUsageResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeEnergy.EnergyUsageResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 powerUsage = 1;</code>
   * @return The powerUsage.
   */
  int getPowerUsage();

  /**
   * <code>string status = 2;</code>
   * @return The status.
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 2;</code>
   * @return The bytes for status.
   */
  com.google.protobuf.ByteString
      getStatusBytes();
}
