// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyRoutineServices.proto

package generated.smarthome.energy;

public interface GoogleHomeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeEnergy.GoogleHomeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string command = 1;</code>
   * @return The command.
   */
  java.lang.String getCommand();
  /**
   * <code>string command = 1;</code>
   * @return The bytes for command.
   */
  com.google.protobuf.ByteString
      getCommandBytes();
}
