// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyRoutineServices.proto

package generated.smarthome.energy;

public interface PowerModeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeEnergy.PowerModeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool enable = 1;</code>
   * @return The enable.
   */
  boolean getEnable();
}
