// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package generated.smarthome.security;

public interface ResponseMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeSecurity.ResponseMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>string message = 2;</code>
   * @return The message.
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
