// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: EnergyRoutineServices.proto

package generated.smarthome.energy;

public final class SmartHomeEnergyImpl {
  private SmartHomeEnergyImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeEnergy_EmptyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeEnergy_EmptyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeEnergy_EnergyUsageResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeEnergy_EnergyUsageResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeEnergy_PowerModeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeEnergy_PowerModeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeEnergy_GoogleHomeRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeEnergy_GoogleHomeRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeEnergy_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeEnergy_ResponseMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033EnergyRoutineServices.proto\022\017SmartHome" +
      "Energy\"\016\n\014EmptyRequest\"9\n\023EnergyUsageRes" +
      "ponse\022\022\n\npowerUsage\030\001 \001(\005\022\016\n\006status\030\002 \001(" +
      "\t\"\"\n\020PowerModeRequest\022\016\n\006enable\030\001 \001(\010\"$\n" +
      "\021GoogleHomeRequest\022\017\n\007command\030\001 \001(\t\"3\n\017R" +
      "esponseMessage\022\017\n\007success\030\001 \001(\010\022\017\n\007messa" +
      "ge\030\002 \001(\t2\261\002\n\024EnergyRoutineService\022Z\n\023Opt" +
      "imizeEnergyUsage\022\035.SmartHomeEnergy.Empty" +
      "Request\032$.SmartHomeEnergy.EnergyUsageRes" +
      "ponse\022\\\n\025EnablePowerSavingMode\022!.SmartHo" +
      "meEnergy.PowerModeRequest\032 .SmartHomeEne" +
      "rgy.ResponseMessage\022_\n\027IntegrateWithGoog" +
      "leHome\022\".SmartHomeEnergy.GoogleHomeReque" +
      "st\032 .SmartHomeEnergy.ResponseMessageB3\n\032" +
      "generated.smarthome.energyB\023SmartHomeEne" +
      "rgyImplP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SmartHomeEnergy_EmptyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHomeEnergy_EmptyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeEnergy_EmptyRequest_descriptor,
        new java.lang.String[] { });
    internal_static_SmartHomeEnergy_EnergyUsageResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHomeEnergy_EnergyUsageResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeEnergy_EnergyUsageResponse_descriptor,
        new java.lang.String[] { "PowerUsage", "Status", });
    internal_static_SmartHomeEnergy_PowerModeRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartHomeEnergy_PowerModeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeEnergy_PowerModeRequest_descriptor,
        new java.lang.String[] { "Enable", });
    internal_static_SmartHomeEnergy_GoogleHomeRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartHomeEnergy_GoogleHomeRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeEnergy_GoogleHomeRequest_descriptor,
        new java.lang.String[] { "Command", });
    internal_static_SmartHomeEnergy_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_SmartHomeEnergy_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeEnergy_ResponseMessage_descriptor,
        new java.lang.String[] { "Success", "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
