// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package generated.smarthome.security;

public final class SmartHomeSecurityImpl {
  private SmartHomeSecurityImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeSecurity_DoorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeSecurity_DoorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeSecurity_ResponseMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeSecurity_ResponseMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeSecurity_StreamRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeSecurity_StreamRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SmartHomeSecurity_CameraFeed_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SmartHomeSecurity_CameraFeed_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025SecurityService.proto\022\021SmartHomeSecuri" +
      "ty\"\035\n\013DoorRequest\022\016\n\006doorID\030\001 \001(\t\"3\n\017Res" +
      "ponseMessage\022\017\n\007success\030\001 \001(\010\022\017\n\007message" +
      "\030\002 \001(\t\"#\n\rStreamRequest\022\022\n\nstreamType\030\001 " +
      "\001(\t\"\036\n\nCameraFeed\022\020\n\010feedData\030\001 \001(\0142\211\002\n\017" +
      "SecurityService\022N\n\010LockDoor\022\036.SmartHomeS" +
      "ecurity.DoorRequest\032\".SmartHomeSecurity." +
      "ResponseMessage\022P\n\nUnlockDoor\022\036.SmartHom" +
      "eSecurity.DoorRequest\032\".SmartHomeSecurit" +
      "y.ResponseMessage\022T\n\017GetSecurityFeed\022 .S" +
      "martHomeSecurity.StreamRequest\032\035.SmartHo" +
      "meSecurity.CameraFeed0\001B7\n\034generated.sma" +
      "rthome.securityB\025SmartHomeSecurityImplP\001" +
      "b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SmartHomeSecurity_DoorRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SmartHomeSecurity_DoorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeSecurity_DoorRequest_descriptor,
        new java.lang.String[] { "DoorID", });
    internal_static_SmartHomeSecurity_ResponseMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_SmartHomeSecurity_ResponseMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeSecurity_ResponseMessage_descriptor,
        new java.lang.String[] { "Success", "Message", });
    internal_static_SmartHomeSecurity_StreamRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_SmartHomeSecurity_StreamRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeSecurity_StreamRequest_descriptor,
        new java.lang.String[] { "StreamType", });
    internal_static_SmartHomeSecurity_CameraFeed_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_SmartHomeSecurity_CameraFeed_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SmartHomeSecurity_CameraFeed_descriptor,
        new java.lang.String[] { "FeedData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
