// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SecurityService.proto

package generated.smarthome.security;

public interface StreamRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SmartHomeSecurity.StreamRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string streamType = 1;</code>
   * @return The streamType.
   */
  java.lang.String getStreamType();
  /**
   * <code>string streamType = 1;</code>
   * @return The bytes for streamType.
   */
  com.google.protobuf.ByteString
      getStreamTypeBytes();
}
